### ISSUE TITLE
麦克风无法使用

### ISSUE THREAD

**Issue by alexkie007** [huihut/Hackintosh-Z370#1]
你好 。按照你的教程进行了安装，基本完美，现在有两个问题，不知道能否指导一下，
1. 开机时只能插入一个显示器，如果两个显示器同时插入，则会黑屏，只能强行断电。如果开机时只插一个，进入系统后才能插另外一个，则可以正常使用。
2. 电脑的声卡能够正常的听歌 等等，但是麦克风功能无法使用，插入了一个外置的麦克风，但是完全无法录入声音。

**Comment by huihut** [comment]
@alexkie007

1. 抱歉我没有测试过两台显示器的情况
2. 我的能驱动麦克风、耳机、扬声器

* config用的就是： <https://github.com/huihut/Hackintosh-Z370/blob/master/EFI/CLOVER/config.plist>
* 内核补丁如图：
![image](https://user-images.githubusercontent.com/23519480/54544837-5e48b700-49db-11e9-91e7-12528c89f582.png)

**Comment by alexkie007** [comment]
多谢大佬 我换了一个麦克风就好了 原来是麦克风坏掉了， 请问能够核显加速吗？

**Comment by huihut** [comment]
不清楚，没接触过核显加速
